spring.application.name=client
#MySQL DataSource properties
spring.datasource.url=jdbc:mysql://localhost:3306/myjdbc
spring.datasource.username=root
spring.datasource.password=Anusha@1512
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate properties (optional, but commonly used)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect